### ISSUE TITLE
monthly job didn't run for the last day of month

### ISSUE THREAD

**Issue by novanxyz** [odpf/transformers#36] opened 2022-06-14 08:15 UTC
Hi team,

I have a `bq2bq` job with window configuration 

```
  window:
    size: 720h
    offset: -48h
    truncate_to: M
```

I expect to have transformation for date 01 to last day of the month,
e.g on April,
I expect got transformation from date 01 - 30.
but currently only got transformation from date 01 - 29
```
[2022-06-13 15:08:12,323] {pod_launcher.py:149} INFO - [2022-06-13 15:08:12] INFO:bumblebee.transformation: create transformation for partition: 2022-04-26 00:00:00+00:00
[2022-06-13 15:08:12,323] {pod_launcher.py:149} INFO - [2022-06-13 15:08:12] INFO:bumblebee.transformation: create transformation for partition: 2022-04-27 00:00:00+00:00
[2022-06-13 15:08:12,323] {pod_launcher.py:149} INFO - [2022-06-13 15:08:12] INFO:bumblebee.transformation: create transformation for partition: 2022-04-28 00:00:00+00:00
[2022-06-13 15:08:12,323] {pod_launcher.py:149} INFO - [2022-06-13 15:08:12] INFO:bumblebee.transformation: create transformation for partition: 2022-04-29 00:00:00+00:00
[2022-06-13 15:08:12,324] {pod_launcher.py:149} INFO - [2022-06-13 15:08:12] INFO:bumblebee.transformation: start transformation job
[2022-06-13 15:08:12,324] {pod_launcher.py:149} INFO - [2022-06-13 15:08:12] INFO:bumblebee.transformation: sql transformation query:
```

after checking, I suspect the logic may related to this line, where the last day generated by windows class not included as the transformation partition.

https://github.com/odpf/transformers/blob/ea1de4f0de3d17d9be7ccefb1e2f3beab1a685f1/task/bq2bq/executor/bumblebee/transformation.py#L393

please kindly check it, and release the fix.
thank you

**Comment by sravankorumilli** [comment] 2022-07-25 08:52
this issue is a duplicate of odpf/optimus#453

**Closed** 2022-07-25 09:10 UTC
